# Generated by Django 5.0 on 2025-04-01 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_accommodation_reserved_accommodation_reserved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
