# Generated by Django 5.0 on 2025-04-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_ownerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UID',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
