# Generated by Django 5.0 on 2025-04-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(choices=[('HKU', 'The University of Hong Kong'), ('CUHK', 'The Chinese University of Hong Kong'), ('HKUST', 'The Hong Kong University of Science and Technology')], default='HKU', max_length=10),
        ),
    ]
