# Generated by Django 5.0 on 2025-04-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='hku_id',
            new_name='UID',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='university',
            field=models.CharField(choices=[('HKU', 'The University of Hong Kong'), ('CUHK', 'The Chinese University of Hong Kong'), ('HKUST', 'The Hong Kong University of Science and Technology')], default='HKU', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='university',
            field=models.CharField(choices=[('HKU', 'The University of Hong Kong'), ('CUHK', 'The Chinese University of Hong Kong'), ('HKUST', 'The Hong Kong University of Science and Technology')], default='HKU', max_length=10),
        ),
    ]
