# Generated by Django 5.0 on 2025-04-29 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_hku_id_studentprofile_uid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='UID',
            new_name='hku_id',
        ),
    ]
