# Generated by Django 5.0 on 2025-04-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_uid_studentprofile_hku_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='hku_id',
            new_name='UID',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='year_of_study',
        ),
    ]
