# Generated by Django 5.0 on 2025-04-29 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_accommodation_geo_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='owner',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='universities_offered',
            field=models.ManyToManyField(limit_choices_to={'is_cedars_staff': True}, related_name='offered_accommodations', to=settings.AUTH_USER_MODEL),
        ),
    ]
