# Generated by Django 5.0 on 2025-04-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_accommodation_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='flat_number',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='floor_number',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='accommodation',
            unique_together={('geo_address', 'flat_number', 'floor_number', 'room_number')},
        ),
    ]
