# Generated by Django 5.0 on 2025-04-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_accommodation_flat_number_accommodation_floor_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='universities_offered',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='universities_offered',
            field=models.JSONField(default=list),
        ),
    ]
