# Generated by Django 5.0 on 2025-04-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_accommodation_universities_offered_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accommodation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='flat_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='floor_number',
            field=models.CharField(max_length=10),
        ),
    ]
